### ISSUE TITLE
interface for set/get

### ISSUE THREAD

**Issue by ergo** [trofrigo/global-variable#2]
Hello,

I would expect a public API solution to allow for programmatic setting/getting values on the storage.

A common scenario that comes to my mind would be:

    someElem.globalStorage.set('key', value)

For example setting initial values from `window.SOME_CONFIG` or other data manipulation if required.

**Comment by rodrigosancho** [comment]
Hi,

I've been working in a new element, global-data, which allows to set, and get any path in the storage. This element throw as well events with every change into the storage. For example:

`<global-data on-subscribe="_onSubscribe" on-unsubscribe="_onUnsubscribe" on-set="_onSet"></global-data>`

This is currently into the development branch.

Anyway, i'm thinking about try to achieve this using the [Redux library](http://redux.js.org/) and the [Polymer element](https://github.com/tur-nr/polymer-redux).

**Comment by ergo** [comment]
Google recently released:
https://google.github.io/uniflow-polymer/

You might be interested in that.

**Comment by rodrigosancho** [comment]
Oh wow! Thank you.
