### ISSUE TITLE
Are there any plans on migrating to Polymer2?

### ISSUE THREAD

**Issue by EliArtist** [trofrigo/global-variable#6]
Are there any plans on migrating global-variable to Polymer2?

**Comment by rodrigosancho** [comment]
Yep, I've been thinking about it, but I don't know when I'll be able to do it.

**Comment by adzadzadz** [comment]
This basically works on hybrid without any problem so far.

**Comment by yorrd** [comment]
@adzadzadz have you already tested in non-hybrid mode? I can't get it to run in a new Polymer 2 project without hybrid mode.

**Comment by adzadzadz** [comment]
@yorrd just had time to test it, it actually works on non-hybrid. If you can post your setup, then we might be able to track the issue down.

**Comment by yorrd** [comment]
@adzadzadz I might have complained too early, there was some different stuff. It seems to work now. Will report back if it doesn't. Still would be nice just to get a version Update to signal that it's compatible thought @trofrigo :)

**Comment by rodrigosancho** [comment]
Thank you @yorrd and @adzadzadz. I've already updated the [README.md](https://github.com/trofrigo/global-variable/blob/master/README.md) to notify the hybrid mode compatibility.
